import http from 'node:http';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname,join} from 'node:path';
import {randomBytes,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import {openDatabase,transaction,nextNumber,cents,computeItems,datePlus,reconcile} from './db.js';
const db=openDatabase(); const here=dirname(fileURLToPath(import.meta.url)); const port=Number(process.env.PORT||3000);
if(process.env.NODE_ENV==='production' && !process.env.ADMIN_EMAIL) throw Error('ADMIN_EMAIL is required in production');
if(process.env.ADMIN_EMAIL && !db.prepare('SELECT COUNT(*) n FROM users').get().n){
 const email=process.env.ADMIN_EMAIL.trim().toLowerCase(),password=process.env.ADMIN_PASSWORD||'';
 if(!/^\S+@\S+\.\S+$/.test(email)||password.length<12)throw Error('Set valid ADMIN_EMAIL and ADMIN_PASSWORD (12+ characters)');
 const salt=randomBytes(16).toString('hex');
 db.prepare("INSERT INTO users(name,email,salt,hash,role) VALUES(?,?,?,?, 'OWNER')").run('Owner',email,salt,scryptSync(password,salt,64).toString('hex'));
}
function json(res,code,data,headers={}) {res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers});res.end(JSON.stringify(data));}
function fail(status,message){const e=new Error(message);e.status=status;throw e;}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>2e6){reject(Object.assign(new Error('Request too large'),{status:413}));req.destroy();}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{});}catch{reject(Object.assign(new Error('Invalid JSON'),{status:400}));}});req.on('error',reject);});}
function hash(s){return createHash('sha256').update(s).digest('hex');}
function auth(req){const token=(req.headers.cookie||'').match(/(?:^|; )sid=([a-f0-9]{64})/)?.[1]; if(!token)return null;const session=db.prepare('SELECT u.id,u.name,u.email,u.role FROM sessions s JOIN users u ON s.user_id=u.id WHERE s.token_hash=? AND s.expires_at>?').get(hash(token),Date.now());return session||null;}
function requireRole(user,allowed){if(!user)fail(401,'Sign in required');if(!allowed.includes(user.role))fail(403,'Permission denied');}
function audit(user,action,entity,id,details=''){db.prepare('INSERT INTO audit(user_id,action,entity,entity_id,details) VALUES(?,?,?,?,?)').run(user?.id||null,action,entity,id,details);}
function today(){return new Date().toISOString().slice(0,10);}
function validDate(s){datePlus(s,0);return s;}
function intId(s){const n=Number(s);if(!Number.isSafeInteger(n)||n<1)fail(400,'Invalid ID');return n;}
function text(s,max=255){return String(s??'').trim().slice(0,max);}
function client(id){const c=db.prepare('SELECT * FROM clients WHERE id=?').get(intId(id));if(!c)fail(404,'Client not found');return c;}
function settings(){return db.prepare('SELECT * FROM settings WHERE id=1').get();}
function snapshot(){return JSON.stringify(settings());}
function issueDocument(kind,b,user){const c=client(b.clientId);const calc=computeItems(b.items);const issue=validDate(b.issueDate||today());const terms=Number(b.paymentTermsDays??c.payment_terms_days);datePlus(issue,terms);const expiry=b.expiryDate?validDate(b.expiryDate):null; if(expiry&&expiry<issue)fail(400,'Expiry date precedes issue date');
 return transaction(db,()=>{const number=nextNumber(db,kind==='quote'?'QT':kind==='purchase_order'?'PO':'INV',Number(issue.slice(0,4)));
 let id;if(kind==='quote'){
  id=db.prepare('INSERT INTO quotes(client_id,number,issue_date,expiry_date,currency,subtotal,discount,tax,total,notes,terms,payment_terms_days,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(c.id,number,issue,expiry,'MYR',calc.subtotal,calc.discount,calc.tax,calc.total,text(b.notes,4000),text(b.terms??settings().quote_terms,4000),terms,user.id).lastInsertRowid;
 }else if(kind==='purchase_order'){
  id=db.prepare('INSERT INTO purchase_orders(client_id,number,issue_date,expiry_date,currency,subtotal,discount,tax,total,notes,terms,payment_terms_days,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(c.id,number,issue,expiry,'MYR',calc.subtotal,calc.discount,calc.tax,calc.total,text(b.notes,4000),text(b.terms??settings().purchase_order_terms,4000),terms,user.id).lastInsertRowid;
 }else{
  id=db.prepare('INSERT INTO invoices(client_id,number,issue_date,due_date,currency,subtotal,discount,tax,total,balance_due,client_name,client_contact,client_email,client_address,company_snapshot,notes,terms,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(c.id,number,issue,datePlus(issue,terms),'MYR',calc.subtotal,calc.discount,calc.tax,calc.total,calc.total,c.company_name,c.contact_name,c.email,c.address,snapshot(),text(b.notes,4000),text(b.terms??settings().invoice_terms,4000),user.id).lastInsertRowid;
 }
 const stmt=db.prepare(`INSERT INTO ${kind==='quote'?'quote_items':kind==='purchase_order'?'purchase_order_items':'invoice_items'}(${kind==='quote'?'quote_id':kind==='purchase_order'?'purchase_order_id':'invoice_id'},position,description,quantity_milli,unit,unit_price,discount_bps,tax_bps,subtotal,discount,tax,total) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`);
 for(const x of calc.lines)stmt.run(id,x.position,x.description,x.quantity_milli,x.unit,x.unit_price,x.discount_bps,x.tax_bps,x.subtotal,x.discount,x.tax,x.total);
 audit(user,kind.toUpperCase()+'_CREATED',kind,id,number);return {id:Number(id),number};});}
function document(kind,id){const table=kind==='quote'?'quotes':kind==='purchase_order'?'purchase_orders':'invoices';const row=db.prepare(`SELECT * FROM ${table} WHERE id=?`).get(id);if(!row)fail(404,'Document not found'); const items=db.prepare(`SELECT * FROM ${kind==='quote'?'quote_items':kind==='purchase_order'?'purchase_order_items':'invoice_items'} WHERE ${kind==='quote'?'quote_id':kind==='purchase_order'?'purchase_order_id':'invoice_id'}=? ORDER BY position`).all(id);return {...row,items,client:client(row.client_id),payments:kind==='invoice'?db.prepare('SELECT * FROM payments WHERE invoice_id=? ORDER BY date,id').all(id):[]};}
function convert(id,user){return transaction(db,()=>{const q=document('quote',id);const existing=db.prepare('SELECT id,number FROM invoices WHERE source_quote_id=?').get(id);if(existing)return {...existing,alreadyConverted:true};if(q.status!=='ACCEPTED')fail(400,'Accept the quotation before converting');const c=q.client,issue=today(),number=nextNumber(db,'INV',Number(issue.slice(0,4)));
 const invId=db.prepare('INSERT INTO invoices(client_id,source_quote_id,number,issue_date,due_date,currency,subtotal,discount,tax,total,balance_due,client_name,client_contact,client_email,client_address,company_snapshot,notes,terms,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(c.id,id,number,issue,datePlus(issue,q.payment_terms_days),q.currency,q.subtotal,q.discount,q.tax,q.total,q.total,c.company_name,c.contact_name,c.email,c.address,snapshot(),q.notes,q.terms,user.id).lastInsertRowid;
 const stmt=db.prepare('INSERT INTO invoice_items(invoice_id,position,description,quantity_milli,unit,unit_price,discount_bps,tax_bps,subtotal,discount,tax,total) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');for(const x of q.items)stmt.run(invId,x.position,x.description,x.quantity_milli,x.unit,x.unit_price,x.discount_bps,x.tax_bps,x.subtotal,x.discount,x.tax,x.total);
 db.prepare("UPDATE quotes SET status='CONVERTED' WHERE id=?").run(id);audit(user,'QUOTE_CONVERTED','quote',id,number);return {id:Number(invId),number,alreadyConverted:false};});}
function csrf(req){const origin=req.headers.origin;if(origin && origin!==`http://${req.headers.host}` && origin!==`https://${req.headers.host}`)fail(403,'Invalid origin');}
async function api(req,res,path){const method=req.method;const user=auth(req);if(method!=='GET')csrf(req);
 if(path==='/api/setup'&&method==='POST'){if(process.env.NODE_ENV==='production')fail(403,'Use ADMIN_EMAIL and ADMIN_PASSWORD for initial setup');if(db.prepare('SELECT COUNT(*) n FROM users').get().n)fail(403,'Setup already complete');const b=await body(req),email=text(b.email,255).toLowerCase(),password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||password.length<12)fail(400,'Use a valid email and password of at least 12 characters');const salt=randomBytes(16).toString('hex'),pass=scryptSync(password,salt,64).toString('hex');db.prepare('INSERT INTO users(name,email,salt,hash,role) VALUES(?,?,?,?,\'OWNER\')').run(text(b.name)||'Owner',email,salt,pass);return json(res,201,{ok:true});}
 if(path==='/api/login'&&method==='POST'){const b=await body(req),u=db.prepare('SELECT * FROM users WHERE email=?').get(text(b.email).toLowerCase());if(!u)fail(401,'Invalid credentials');const actual=scryptSync(String(b.password||''),u.salt,64),expected=Buffer.from(u.hash,'hex');if(!timingSafeEqual(actual,expected))fail(401,'Invalid credentials');const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(hash(token),u.id,Date.now()+7*864e5);return json(res,200,{ok:true},{'Set-Cookie':`sid=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${process.env.HTTPS==='true'?'; Secure':''}`});}
 if(path==='/api/bootstrap'&&method==='GET')return json(res,200,{setup:!db.prepare('SELECT COUNT(*) n FROM users').get().n,user,settings:user?settings():null});
 requireRole(user,['OWNER','FINANCE','STAFF','VIEWER']);
 if(path==='/api/logout'&&method==='POST'){const tok=(req.headers.cookie||'').match(/sid=([a-f0-9]{64})/)?.[1];if(tok)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(tok));return json(res,200,{ok:true},{'Set-Cookie':'sid=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'});}
 if(path==='/api/settings'){if(method==='GET')return json(res,200,settings());requireRole(user,['OWNER']);if(method==='PATCH'){const b=await body(req);const fields=['company_name','registration_no','address','email','phone','bank_name','bank_account','bank_holder','quote_terms','invoice_terms','purchase_order_terms'];const values=fields.map(k=>text(b[k],k.includes('terms')?4000:1000));if(!values[0])fail(400,'Company name required');db.prepare(`UPDATE settings SET ${fields.map(k=>k+'=?').join(',')} WHERE id=1`).run(...values);audit(user,'SETTINGS_UPDATED','settings',1);return json(res,200,settings());}}
 if(path==='/api/users'){requireRole(user,['OWNER']);if(method==='GET')return json(res,200,db.prepare('SELECT id,name,email,role,created_at FROM users').all());if(method==='POST'){const b=await body(req),p=String(b.password||''),role=text(b.role);if(p.length<12||!['OWNER','FINANCE','STAFF','VIEWER'].includes(role))fail(400,'Invalid role or password');const salt=randomBytes(16).toString('hex');const result=db.prepare('INSERT INTO users(name,email,salt,hash,role) VALUES(?,?,?,?,?)').run(text(b.name),text(b.email).toLowerCase(),salt,scryptSync(p,salt,64).toString('hex'),role);audit(user,'USER_CREATED','user',Number(result.lastInsertRowid));return json(res,201,{ok:true});}}
 if(path==='/api/clients'){if(method==='GET')return json(res,200,db.prepare('SELECT * FROM clients ORDER BY company_name').all());requireRole(user,['OWNER','FINANCE','STAFF']);if(method==='POST'){const b=await body(req),name=text(b.company_name);if(!name)fail(400,'Client name required');const term=Number(b.payment_terms_days??30);datePlus(today(),term);const result=db.prepare('INSERT INTO clients(company_name,contact_name,email,phone,address,payment_terms_days,notes) VALUES(?,?,?,?,?,?,?)').run(name,text(b.contact_name),text(b.email),text(b.phone),text(b.address,2000),term,text(b.notes,4000));audit(user,'CLIENT_CREATED','client',Number(result.lastInsertRowid));return json(res,201,{id:Number(result.lastInsertRowid)});}}
 let m=path.match(/^\/api\/clients\/(\d+)$/);if(m){const id=intId(m[1]);const c=client(id);if(method==='GET')return json(res,200,c);requireRole(user,['OWNER','FINANCE','STAFF']);if(method==='PATCH'){const b=await body(req);const term=Number(b.payment_terms_days??c.payment_terms_days);datePlus(today(),term);const name=text(b.company_name??c.company_name);if(!name)fail(400,'Client name required');db.prepare('UPDATE clients SET company_name=?,contact_name=?,email=?,phone=?,address=?,payment_terms_days=?,notes=? WHERE id=?').run(name,text(b.contact_name??c.contact_name),text(b.email??c.email),text(b.phone??c.phone),text(b.address??c.address,2000),term,text(b.notes??c.notes,4000),id);audit(user,'CLIENT_UPDATED','client',id);return json(res,200,{ok:true});}}
 if(path==='/api/quotes'||path==='/api/invoices'||path==='/api/purchase-orders'){const kind=path==='/api/quotes'?'quote':path==='/api/invoices'?'invoice':'purchase_order';if(method==='GET')return json(res,200,db.prepare(`SELECT d.*,c.company_name FROM ${kind==='quote'?'quotes':kind==='purchase_order'?'purchase_orders':'invoices'} d JOIN clients c ON c.id=d.client_id ORDER BY d.id DESC LIMIT 500`).all());requireRole(user,['OWNER','FINANCE','STAFF']);if(method==='POST')return json(res,201,issueDocument(kind,await body(req),user));}
 m=path.match(/^\/api\/(quotes|invoices|purchase-orders)\/(\d+)(?:\/(send|accept|reject|approve|convert|void|payments))?$/);if(m){const kind=m[1]==='quotes'?'quote':m[1]==='invoices'?'invoice':'purchase_order',id=intId(m[2]),action=m[3];const d=document(kind,id);if(method==='GET'&&!action)return json(res,200,d);if(method==='GET'&&action==='payments'&&kind==='invoice')return json(res,200,d.payments);requireRole(user,action==='payments'||action==='void'?['OWNER','FINANCE']:['OWNER','FINANCE','STAFF']);if(method==='POST'&&kind==='quote'&&['send','accept','reject'].includes(action)){const allowed={send:['DRAFT'],accept:['SENT','DRAFT'],reject:['SENT','DRAFT']};if(!allowed[action].includes(d.status))fail(400,'Invalid status change');const status={send:'SENT',accept:'ACCEPTED',reject:'REJECTED'}[action];db.prepare('UPDATE quotes SET status=? WHERE id=?').run(status,id);audit(user,'QUOTE_'+status,'quote',id);return json(res,200,{status});}if(method==='POST'&&kind==='purchase_order'&&['send','approve','reject'].includes(action)){const allowed={send:['DRAFT'],approve:['SENT','DRAFT'],reject:['SENT','DRAFT']};if(!allowed[action].includes(d.status))fail(400,'Invalid status change');const status={send:'SENT',approve:'APPROVED',reject:'REJECTED'}[action];db.prepare('UPDATE purchase_orders SET status=? WHERE id=?').run(status,id);audit(user,'PO_'+status,'purchase_order',id);return json(res,200,{status});}if(method==='POST'&&kind==='quote'&&action==='convert')return json(res,200,convert(id,user));
 if(method==='POST'&&kind==='invoice'&&action==='send'){if(d.status!=='DRAFT')fail(400,'Only draft invoices can be sent');db.prepare("UPDATE invoices SET status='SENT',sent_at=CURRENT_TIMESTAMP WHERE id=?").run(id);audit(user,'INVOICE_SENT','invoice',id);return json(res,200,{ok:true});}
 if(method==='POST'&&kind==='invoice'&&action==='void'){if(d.amount_paid>0)fail(400,'Reverse recorded payments before voiding');if(d.status==='VOID')fail(400,'Already void');db.prepare("UPDATE invoices SET status='VOID',balance_due=0 WHERE id=?").run(id);audit(user,'INVOICE_VOIDED','invoice',id);return json(res,200,{ok:true});}
 if(method==='POST'&&kind==='invoice'&&action==='payments'){if(d.status==='VOID')fail(400,'Cannot pay void invoice');const b=await body(req),amount=cents(b.amount),date=validDate(b.date||today());if(amount<=0||amount>d.balance_due)fail(400,'Payment must be positive and at most the balance');return json(res,201,transaction(db,()=>{const result=db.prepare('INSERT INTO payments(invoice_id,date,amount,method,reference,notes,created_by) VALUES(?,?,?,?,?,?,?)').run(id,date,amount,text(b.method)||'Bank transfer',text(b.reference),text(b.notes,1000),user.id);reconcile(db,id);audit(user,'PAYMENT_RECORDED','payment',Number(result.lastInsertRowid));return {id:Number(result.lastInsertRowid)};}));}}
 m=path.match(/^\/api\/payments\/(\d+)$/);if(m&&method==='DELETE'){requireRole(user,['OWNER','FINANCE']);const id=intId(m[1]);const p=db.prepare('SELECT * FROM payments WHERE id=?').get(id);if(!p)fail(404,'Payment not found');return json(res,200,transaction(db,()=>{db.prepare('DELETE FROM payments WHERE id=?').run(id);reconcile(db,p.invoice_id);audit(user,'PAYMENT_REMOVED','payment',id,JSON.stringify(p));return {ok:true};}));}
 if(path==='/api/expenses'){if(method==='GET')return json(res,200,db.prepare('SELECT * FROM expenses ORDER BY date DESC,id DESC LIMIT 500').all());requireRole(user,['OWNER','FINANCE']);if(method==='POST'){const b=await body(req),amount=cents(b.amount);if(amount<=0)fail(400,'Positive amount required');const result=db.prepare('INSERT INTO expenses(date,category,vendor,description,amount,reference) VALUES(?,?,?,?,?,?)').run(validDate(b.date||today()),text(b.category),text(b.vendor),text(b.description,1000),amount,text(b.reference));audit(user,'EXPENSE_CREATED','expense',Number(result.lastInsertRowid));return json(res,201,{id:Number(result.lastInsertRowid)});}}
 if(path==='/api/dashboard'&&method==='GET'){const invoiced=db.prepare("SELECT COALESCE(SUM(total),0) n FROM invoices WHERE status!='VOID'").get().n;const cash=db.prepare('SELECT COALESCE(SUM(amount),0) n FROM payments').get().n;const outstanding=db.prepare("SELECT COALESCE(SUM(balance_due),0) n FROM invoices WHERE status NOT IN ('DRAFT','VOID')").get().n;const overdue=db.prepare("SELECT COALESCE(SUM(balance_due),0) n FROM invoices WHERE status NOT IN ('DRAFT','VOID') AND due_date < ?").get(today()).n;const monthly=db.prepare("SELECT substr(date,1,7) month, SUM(amount) amount, 'in' kind FROM payments GROUP BY 1 UNION ALL SELECT substr(date,1,7),SUM(amount),'out' FROM expenses GROUP BY 1 ORDER BY 1").all();const aging=db.prepare("SELECT CASE WHEN due_date>=? THEN 'Current' WHEN julianday(?) - julianday(due_date)<=30 THEN '1–30 days' WHEN julianday(?) - julianday(due_date)<=60 THEN '31–60 days' WHEN julianday(?) - julianday(due_date)<=90 THEN '61–90 days' ELSE '90+ days' END bucket,SUM(balance_due) amount FROM invoices WHERE balance_due>0 AND status NOT IN ('DRAFT','VOID') GROUP BY bucket").all(today(),today(),today(),today());return json(res,200,{invoiced,cash,outstanding,overdue,monthly,aging,quotes:db.prepare('SELECT status,COUNT(*) count FROM quotes GROUP BY status').all(),recent:db.prepare('SELECT id,number,client_name,total,balance_due,status,due_date FROM invoices ORDER BY id DESC LIMIT 7').all()});}
 m=path.match(/^\/api\/clients\/(\d+)\/statement$/);if(m&&method==='GET'){const id=intId(m[1]),c=client(id);const inv=db.prepare("SELECT id,issue_date date,number reference,total amount,'invoice' type FROM invoices WHERE client_id=? AND status!='VOID'").all(id);const payments=db.prepare("SELECT p.id,p.date,i.number reference,p.amount,'payment' type FROM payments p JOIN invoices i ON i.id=p.invoice_id WHERE i.client_id=? AND i.status!='VOID'").all(id);return json(res,200,{client:c,entries:[...inv,...payments].sort((a,b)=>a.date.localeCompare(b.date)||a.type.localeCompare(b.type))});}
 if(path==='/api/audit'&&method==='GET'){requireRole(user,['OWNER','FINANCE']);return json(res,200,db.prepare('SELECT a.*,u.name user_name FROM audit a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 200').all());}
 fail(404,'Not found');}
const attempts=new Map();
const files={'/':'index.html','/app.js':'app.js','/style.css':'style.css'};
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,`http://${req.headers.host||'localhost'}`).pathname;if(path==='/api/login' && req.method==='POST'){const ip=req.socket.remoteAddress||'unknown',now=Date.now(),entry=attempts.get(ip)||{count:0,until:now+900000};if(now>entry.until){entry.count=0;entry.until=now+900000}if(entry.count>=20)fail(429,'Too many login attempts; try later');entry.count++;attempts.set(ip,entry);if(attempts.size>10000)attempts.clear()}if(path.startsWith('/api/'))return await api(req,res,path);if(req.method!=='GET'||!files[path])fail(404,'Not found');const file=readFileSync(join(here,'public',files[path]));res.writeHead(200,{'Content-Type':path.endsWith('.js')?'text/javascript; charset=utf-8':path.endsWith('.css')?'text/css; charset=utf-8':'text/html; charset=utf-8','Content-Security-Policy':"default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'",'X-Content-Type-Options':'nosniff'});res.end(file);}catch(e){if(!res.headersSent)json(res,e.status||400,{error:e.message||'Request failed'});}});
server.listen(port,process.env.HOST||'127.0.0.1',()=>console.log(`Open http://localhost:${port}`));
